ROJECT3: Set associations
AbdimulhinYussuf3675/OOP-school-library pull request #5
Opened 2023-04-14 19:57 UTC by AbdimulhinYussuf3675

In this branch, I was able to implement;

- [x] Created a class Classroom with @Label instance variable
- [x] Created the has-many/belongs-to relationship between Classroom and Student.
- [x] Created a class Book with @title and its instance variables
- [x] Created a class Rental with @Date instance variables
- [x] Created the many-to-many relationship between Person and Book
- [x] Fixed linter errors

2023-04-14 20:10 UTC, mikethreels requested changes
Hi Adan, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
- Good job setting up the associations.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-14 20:10 UTC, mikethreels commented on classroom.rb
> +  attr_accessor :label, student
- [ ] for the student in this case only setting the reader would suffice, also make sure to use the full colon ":" otherwise it will not work

2023-04-14 20:10 UTC, mikethreels commented on student.rb
> +  end
- [ ] Please make sure to set the attribute reader for classroom in this class as well in order to make the has-many/belongs-to relationship work.

2023-04-14 20:10 UTC, mikethreels commented on student.rb
> +  end
- [ ] Please make sure to check if the student is already in the classroom or not before pushing it to the classroom

2023-04-15 08:04 UTC, PinkMoon25 approved these changes
Hi @AbdimulhinYussuf3675 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Rubocop checks :heavy_check_mark: 
gitflow :heavy_check_mark: 
Assosciations :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-15 08:05 UTC, merged